
source "vagrant" "autogenerated_1" {
  add_force    = true
  communicator = "ssh"
  provider     = "virtualbox"
  source_path  = "ubuntu/bionic64"
}

build {
  sources = ["source.vagrant.autogenerated_1"]

  provisioner "ansible" {
    playbook_file    = "./main.yml"
    roles_path       = "/roles/"
    extra_arguments = ["--extra-vars", "ansible_python_interpreter=/usr/bin/python3"]
  }
}