---
# defaults file for common
timezone: America/Sao_Paulo
root_default_pass: "qaz123"
tux_default_pass: "qaz123"

common_debian:
  - build-essential
  - net-tools
  - bc
  - sudo
  - screen
  - tcpdump
  - telnet
  - nmap
  - vim
  - tree

common_redhat:
  - "@Development tools"
  - bind-utils
  - bc
  - bzip2
  - curl
  - elinks
  - git
  - htop
  - iperf3
  - iptraf
  - lsof
  - lynx
  - mtr
  - net-tools
  - nmap
  - pv
  - screen
  - tcpdump
  - telnet
  - unzip
  - vim
  - wget
  - aspell
  - bash-completion
  - tree